export const TRAILS = [
  // Hidden Gems
  {
    id: 'hirikatuoya',
    name: 'Hirikatuoya',
    location: 'Belihuloya',
    difficulty: 'Easy',
    description: "A hidden paradise in Belihuloya where cool mountain streams flow over smooth rocks. It's perfect for a refreshing natural bath after a short hike through the woods.",
    elevation: '650m',
    duration: '30 Mins',
    climate: 'Humid & Tropical',
    hiddenGem: true,
    image: require('@/assets/images/hirikatuoya.jpeg'),
    images: [
      require('@/assets/images/hirikatuoya.jpeg'),
      require('@/assets/images/hirikatuoya_2.jpeg'),
      require('@/assets/images/hirikatuoya_3.jpeg'),
    ],
    safetyTips: ['Check water levels before entering.', 'Respect the local environment.'],
  },
  {
    id: 'bakers-bend',
    name: "Baker's Bend",
    location: 'Nonpareil Estate',
    difficulty: 'Hard',
    description: "This horseshoe-shaped viewpoint on the Nonpareil estate road offers a dramatic drop and sweeping views of the southern plains. It's often shrouded in mist, giving it a mysterious and grand feel.",
    elevation: '1,450m',
    duration: '4 Hours',
    climate: 'Misty & Windy',
    hiddenGem: true,
    image: require('@/assets/images/bakers bend.jpeg'),
    images: [
      require('@/assets/images/bakers bend.jpeg'),
      require('@/assets/images/bakers_bend_2.jpeg'),
      require('@/assets/images/bakers_bend_3.jpeg'),
    ],
    safetyTips: ['Strong winds at the bend.', 'Fog can reduce visibility quickly.'],
  },
  {
    id: 'hawagala',
    name: 'Hawagala ',
    location: 'Belihuloya',
    difficulty: 'Hard',
    description: "A majestic peak shaped like a hawk's wing, offering a 360-degree panoramic view of the Samanala Wewa reservoir and the surrounding mountain ranges. The golden grasslands at the summit are simply magical at sunrise.",
    elevation: '1,350m',
    duration: '5 Hours',
    climate: 'Cool & Sunny',
    hiddenGem: true,
    image: require('@/assets/images/hawagala.jpeg'),
    safetyTips: ['Carry plenty of water.', 'Start early to avoid the sun.'],
  },
  {
    id: 'narangala',
    name: 'Narangala ',
    location: 'Badulla',
    difficulty: 'Moderate',
    description: "Known for its iconic razor-sharp ridge and vast golden meadows. Standing on the peak feels like you're on top of the world, with clouds drifting right beneath your feet.",
    elevation: '1,500m',
    duration: '4 Hours',
    climate: 'Windy & Cool',
    hiddenGem: true,
    image: 'https://scontent-bom2-4.xx.fbcdn.net/v/t39.30808-6/477449241_931815885703865_8952242074125141801_n.jpg?stp=dst-jpg_s640x640_tt6&_nc_cat=106&ccb=1-7&_nc_sid=127cfc&_nc_ohc=jl0KGS1KVi8Q7kNvwES6AdW&_nc_oc=Adoy60pxbWzkPsMKc7R3kj65271aiVo8p5l_9v1GjUXGqdtox_WRTQ1jVYIOGb5Vpp6E6uDNnFG0KR-0djiT6YdM&_nc_zt=23&_nc_ht=scontent-bom2-4.xx&_nc_gid=MMl6O5xbp0auoAl4FouDbA&_nc_ss=7b289&oh=00_Af70yiZigJXco2Iyjxf2Vh78dqAiqkgrRSHuXfQjMcwiRg&oe=6A0E6C9F',
    safetyTips: ['Ridge can be slippery when wet.', 'Stay on the marked paths.'],
  },
  {
    id: 'wangedigala',
    name: 'Wangedigala',
    location: 'Belihuloya',
    difficulty: 'Hard',
    description: "A steep and rewarding climb through pine forests that leads to a sharp rock outcrop. From here, you can see the entire Belihuloya valley stretched out in all its glory.",
    elevation: '1,320m',
    duration: '4 Hours',
    climate: 'Pine-scented & Cool',
    hiddenGem: true,
    image: require('@/assets/images/wangedigala.jpeg'),
    safetyTips: ['Steep rocky sections.', 'Wear boots with good grip.'],
  },
  {
    id: 'pahanthudawa',
    name: 'Pahanthudawa Waterfall',
    location: 'Belihuloya',
    difficulty: 'Easy',
    description: "A unique waterfall falling into a pool that resembles a traditional 'Pahana' (oil lamp). Tucked away in a lush valley, it's a serene spot for nature lovers and photographers.",
    elevation: '650m',
    duration: '30 Mins',
    climate: 'Humid & Lush',
    hiddenGem: true,
    image: require('@/assets/images/pahanthudawa.jpeg'),
    safetyTips: ['Rocks are slippery.', 'Do not jump into the pool.'],
  },
  {
    id: 'hunugalpokuna',
    name: 'Hunugalpokuna',
    location: 'Limestone Pond, Balangoda',
    difficulty: 'Easy',
    description: "A rare limestone pond with crystal clear, turquoise water hidden deep in the Balangoda region. It's a peaceful oasis perfect for a quiet picnic away from the crowds.",
    elevation: '600m',
    duration: '30 Mins',
    climate: 'Tropical & Still',
    hiddenGem: true,
    image: require('@/assets/images/hunugalpokuna.jpeg'),
    images: [
      require('@/assets/images/hunugalpokuna.jpeg'),
      require('@/assets/images/hunugalpokuna_2.jpeg'),
      require('@/assets/images/hunugalpokuna_3.jpeg'),
    ],
    safetyTips: ['Water can be deep in areas.', 'Keep the area clean.'],
  },
  {
    id: 'gartmore',
    name: 'Gartmore Falls',
    location: 'Maskeliya',
    difficulty: 'Moderate',
    description: "Also known as the Sri Pada Falls, this massive cascade drops directly into the Maskeliya Reservoir. The view of the falls with Adam's Peak in the distance is truly soul-stirring.",
    elevation: '1,200m',
    duration: '2 Hours',
    climate: 'Misty & Fresh',
    hiddenGem: true,
    image: require('@/assets/images/gartmorefalls.jpeg'),
    safetyTips: ['Can be very misty.', 'Leech protection is recommended.'],
  },
  {
    id: 'alien-rock',
    name: 'Alien faced Rock / Galapitagala',
    location: 'Kalupahana, Badulla',
    difficulty: 'Moderate',
    description: "A mysterious geological formation in Kalupahana, known locally as Galapitagala (or Hellena Gala). It is famous for its uncanny resemblance to an extraterrestrial face and features a massive boulder balancing precariously on a smaller rock base.",
    elevation: '1,100m',
    duration: '2 Hours',
    climate: 'Misty & Cool',
    hiddenGem: true,
    coordinates: { lat: 6.7812, lon: 80.8248 },
    image: require('@/assets/images/alien.jpeg'),
    safetyTips: ['Steep pine slopes can be slippery.', 'Carry sun and wind protection.', 'Do not climb the balancing rock.'],
  },
  {
    id: 'alien-waterfall',
    name: 'Alien Waterfall / Nidangoda Ella',
    location: 'Kalupahana, Badulla',
    difficulty: 'Moderate',
    description: "Tucked away in the Galapitiyaya Estate near Kalupahana, this waterfall is famously dubbed the 'Alien Waterfall' due to the surreal, smooth, wave-like dark rock formations over which the water flows, giving the landscape an otherworldly appearance.",
    elevation: '1,050m',
    duration: '2 Hours',
    climate: 'Misty & Humid',
    hiddenGem: true,
    coordinates: { lat: 6.7845, lon: 80.8285 },
    image:  require('@/assets/images/nidangoda.jpeg'),
    safetyTips: ['Rocks near the cascade are extremely slippery.', 'Wear leech protection during wet seasons.', 'Ask for local guidance as the forest path can be tricky.'],
  },
  {
    id: 'aadara-kanda',
    name: 'Aadara Kanda / Paraviyangala',
    location: 'Belihuloya',
    difficulty: 'Moderate',
    description: "Commonly called the 'Mountain of Love', this trail is a favorite for campers. The rolling hills and the view of the Samanala Wewa under a blanket of stars are unforgettable.",
    elevation: '1,100m',
    duration: '4 Hours',
    climate: 'Cool & Breezy',
    hiddenGem: true,
    image:require('@/assets/images/aadara.jpeg'),
    safetyTips: ['Great for camping but pack out trash.', 'Mist is common in evenings.'],
  },
  {
    id: 'nonpareil',
    name: 'Nonpareil Estate',
    location: 'Belihuloya',
    difficulty: 'Easy',
    description: "A leisurely walk through historic tea plantations where you can see the daily lives of estate workers. The road winds through emerald green hills with frequent waterfalls appearing at every turn.",
    elevation: '1,200m',
    duration: '2 Hours',
    climate: 'Fresh & Cool',
    hiddenGem: true,
    image:  require('@/assets/images/nonpareil.jpeg'),
    images: [
      require('@/assets/images/nonpareil.jpeg'),
      require('@/assets/images/nonpareil_2.jpeg'),
      require('@/assets/images/nonpareil_3.jpeg'),
    ],
    safetyTips: ['Respect the estate workers.', 'Stay on the estate roads.'],
  },
  {
    id: 'lanka-ella',
    name: 'Lanka Ella',
    location: 'Kalupahana',
    difficulty: 'Moderate',
    description: "Hidden deep within the Kalupahana forest, this waterfall is uniquely shaped like the map of Sri Lanka. It's a true explorer's destination, reachable only through a rugged jungle trek.",
    elevation: '1,150m',
    duration: '3 Hours',
    climate: 'Jungle Humid',
    hiddenGem: true,
    image: require('@/assets/images/lanka.jpeg'),
    safetyTips: ['Trail can be confusing.', 'Use a local guide if possible.'],
  },
  {
    id: 'kalthota',
    name: 'Kalthota Doowili Ella',
    location: 'Balangoda',
    difficulty: 'Hard',
    description: "A massive, powerful waterfall that creates a constant 'dust' of water spray. The remote location and the raw power of the water make it one of the most adventurous spots in Balangoda.",
    elevation: '300m',
    duration: '1 Hour',
    climate: 'Wild & Humid',
    hiddenGem: true,
    image: require('@/assets/images/doowili.jpeg'),
    safetyTips: ['Remote area, go in a group.', 'Carry enough food and water.'],
  },
  {
    id: 'devils-staircase',
    name: "Devil's Staircase",
    location: 'Ohiya',
    difficulty: 'Hard',
    description: "One of the most challenging and scenic mountain passes in the country. The trail zig-zags through steep tea estates and offers some of the most dramatic cliff-side views in Sri Lanka.",
    elevation: '1,800m',
    duration: '7 Hours',
    climate: 'Cold & Misty',
    hiddenGem: true,
    image: require('@/assets/images/devil.jpeg'),
    safetyTips: ['Long endurance hike.', 'Ensure your knees are healthy.'],
  },
  {
    id: 'thangamale',
    name: 'Thangamale Sanctuary',
    location: 'Haputale',
    difficulty: 'Easy',
    description: "A protected sanctuary in Haputale teeming with endemic birdlife. The trail follows a peaceful ridge overlooking the southern plains and the historic Adisham Bungalow.",
    elevation: '1,400m',
    duration: '2 Hours',
    climate: 'Cool & Quiet',
    hiddenGem: true,
    image: require('@/assets/images/thangamale.jpeg'),
    safetyTips: ['Keep noise levels low.', 'Great for bird watching.'],
  },

  // Popular Trails
  {
    id: 'liptons-seat',
    name: "Lipton's Seat",
    location: 'Haputale',
    difficulty: 'Easy',
    description: "The legendary lookout where Sir Thomas Lipton used to survey his vast tea empire. On a clear day, you can see across five provinces, with the emerald green tea bushes stretching as far as the eye can see.",
    elevation: '1,970m',
    duration: '3 Hours',
    climate: 'Chilly & Windy',
    hiddenGem: false,
    image: require('@/assets/images/lipton.jpeg'),
    images: [
      require('@/assets/images/lipton.jpeg'),
      require('@/assets/images/lipton_2.jpeg'),
      require('@/assets/images/lipton_3.jpeg'),
    ],
    safetyTips: ['Visit before 9 AM.', 'Can get very chilly.'],
  },
  {
    id: 'bambarakanda',
    name: 'Bambarakanda Falls',
    location: 'Kalupahana',
    difficulty: 'Easy',
    description: "The tallest waterfall in Sri Lanka, plunging down a vertical cliff face. A short, pine-scented hike leads you to the base where you can feel the raw power of the water crashing from 263 meters above.",
    elevation: '1,100m',
    duration: '30 Mins',
    climate: 'Misty & Cool',
    hiddenGem: false,
    image: require('@/assets/images/trails/bambarakanda.png'),
    safetyTips: ['Rocks are extremely slippery.', 'Avoid during heavy rains.'],
  },
  {
    id: 'adams-peak',
    name: "Adam's Peak / Sri Pada",
    location: 'Nallathanniya, Maskeliya',
    difficulty: 'Hard',
    description: "A sacred mountain revered by multiple religions, famous for the 'Sri Pada' (sacred footprint) at its summit. The traditional climb via Nallathanniya starts at night to reach the peak before dawn, rewarding hikers with a breathtaking sunrise and the mountain's iconic triangular shadow.",
    elevation: '2,243m',
    duration: '5 Hours',
    climate: 'Cold & Windy',
    hiddenGem: false,
    image: require("@/assets/images/adam's_peak.jpg"),
    coordinates: { lat: 6.8092, lon: 80.4996 },
    safetyTips: ['Wear warm layers; it gets very cold at the summit.', 'Start early (around midnight) to catch the sunrise.', 'Be prepared for a steep climb of over 5,000 steps.'],
  },
  {
    id: 'nine-arch',
    name: 'Nine Arch Bridge',
    location: 'Ella',
    difficulty: 'Easy',
    description: "An architectural masterpiece hidden in the lush tea fields of Ella. Watching the blue train glide over the nine stone arches while the surrounding valley is draped in mist is a bucket-list experience for every traveler.",
    elevation: '1,100m',
    duration: '1 Hour',
    climate: 'Tropical & Misty',
    hiddenGem: false,
    image: require('@/assets/images/ninearch.jpeg'),
    safetyTips: ['Check train times.', 'Watch your step on the tracks.'],
  },
  {
    id: 'diyaluma',
    name: 'Diyaluma Falls',
    location: 'Koslanda',
    difficulty: 'Moderate',
    description: "The second highest waterfall in Sri Lanka, famous for its 'Upper Diyaluma' pools. The hike to the top rewards you with multiple natural infinity pools perched right at the edge of a dizzying 220-meter drop.",
    elevation: '600m',
    duration: '1.5 Hours',
    climate: 'Sunny & Refreshing',
    hiddenGem: false,
    image: require('@/assets/images/diya.jpeg'),
    safetyTips: ['Edge of pools is dangerous.', 'Swim with caution.'],
  },
  {
    id: 'adisham',
    name: 'Adisham Bungalow',
    location: 'Haputale',
    difficulty: 'Easy',
    description: "A piece of old England in the heart of Sri Lanka. This Benedictine monastery, originally a country house, is surrounded by orchards and a peaceful forest trail that feels like stepping back in time.",
    elevation: '1,500m',
    duration: '1 Hour',
    climate: 'Cool & English',
    hiddenGem: false,
    image: require('@/assets/images/bunglow.jpeg'),
    images: [
      require('@/assets/images/bunglow.jpeg'),
      require('@/assets/images/bunglow_2.jpeg'),
      require('@/assets/images/bunglow_3.jpeg'),
    ],
    safetyTips: ['Respect the monastery silence.', 'Check visiting hours.'],
  },
  {
    id: 'ella-rock',
    name: 'Ella Rock',
    location: 'Ella',
    difficulty: 'Hard',
    description: "The most iconic hike in Ella. The trail takes you through railway tracks and dense rubber forests before a steep climb to the summit, where you're rewarded with a breathtaking bird's-eye view of the Ella Gap.",
    elevation: '1,300m',
    duration: '4 Hours',
    climate: 'Tropical & Breezy',
    hiddenGem: false,
    image:  require('@/assets/images/ellarock.jpeg'),
    safetyTips: ['Can be hard to find without a guide.', 'Beware of false guides.'],
  },
  {
    id: 'horton-plains',
    name: 'Horton Plains',
    location: 'Nuwara Eliya',
    difficulty: 'Easy',
    description: "A UNESCO World Heritage site and a plateau of silent beauty. The 9km circular trail takes you through cloud forests and damp grasslands, leading to the famous World's End precipice.",
    elevation: '2,100m',
    duration: '4 Hours',
    climate: 'Cold & Damp',
    hiddenGem: false,
    image: require('@/assets/images/horton.jpeg'),
    images: [
      require('@/assets/images/horton.jpeg'),
      require('@/assets/images/horton_2.jpeg'),
      require('@/assets/images/horton_3.jpeg'),
    ],
    safetyTips: ['Strict no-plastic policy.', 'Be prepared for rain.'],
  },
  {
    id: 'ohiya-scenic',
    name: 'Ohiya Scenic Route',
    location: 'Ohiya',
    difficulty: 'Easy',
    description: "A unique rail-side walk that takes you through historic tunnels and misty pine forests. It's one of the most atmospheric trails in the highlands, especially when the afternoon mist rolls in.",
    elevation: '1,700m',
    duration: '2 Hours',
    climate: 'Misty & Quiet',
    hiddenGem: false,
    image: require('@/assets/images/ohiya.jpeg'),
    images: [
      require('@/assets/images/ohiya.jpeg'),
      require('@/assets/images/ohiya_2.jpeg'),
      require('@/assets/images/ohiya_3.jpeg'),
    ],
    safetyTips: ['Railway tracks are in use.', 'Watch for the train.'],
  },
  {
    id: 'worlds-end',
    name: "World's End",
    location: 'Horton Plains',
    difficulty: 'Easy',
    description: "Sri Lanka's most famous drop. Standing at the edge of this 4,000-foot sheer precipice feels like looking off the edge of the planet. The best time is at dawn before the clouds obscure the view.",
    elevation: '2,100m',
    duration: '4 Hours',
    climate: 'Freezing & Misty',
    hiddenGem: false,
    image: require('@/assets/images/world.jpeg'),
    images: [
      require('@/assets/images/world.jpeg'),
      require('@/assets/images/world_2.jpeg'),
      require('@/assets/images/world_3.jpeg'),
    ],
    safetyTips: ['Do not lean over the edge.', 'Early morning is best.'],
  },
  {
    id: 'moon-plains',
    name: 'Moon Plains',
    location: 'Nuwara Eliya',
    difficulty: 'Easy',
    description: "A vast, high-altitude grassland that offers a stunning 360-degree view of the central highlands. It's one of the few places where you can see all the major peaks of Sri Lanka in one sweep.",
    elevation: '1,900m',
    duration: '2 Hours',
    climate: 'Windy & Sunny',
    hiddenGem: false,
    image: require('@/assets/images/moon.jpeg'),
    safetyTips: ['Can be very windy.', 'No shade, wear a hat.'],
  },
  {
    id: 'surathali',
    name: 'Surathali Ella',
    location: 'Belihuloya',
    difficulty: 'Easy',
    description: "Named after a famous Sri Lankan film, this graceful waterfall is visible right from the main Badulla-Colombo road. It's a perfect spot for a quick break and a few photos of the delicate water veil.",
    elevation: '700m',
    duration: '0.5 Hours',
    climate: 'Humid & Tropical',
    hiddenGem: false,
    image: require('@/assets/images/surathi.jpeg'),
    safetyTips: ['Keep children close by.', 'Accessible from the A15.'],
  },
  {
    id: 'samanala-wewa',
    name: 'Samanala Wewa Reservoir',
    location: 'Belihuloya',
    difficulty: 'Easy',
    description: "A colossal man-made reservoir that looks like a natural lake. The trail follows the edge of the dam, offering peaceful views of the Samanala mountains reflected in the deep blue waters.",
    elevation: '500m',
    duration: '1 Hour',
    climate: 'Sunny & Breezy',
    hiddenGem: false,
    image: require('@/assets/images/samanalawewa.jpeg'),
    safetyTips: ['Dams are restricted areas.', 'Stay within public paths.'],
  },
  {
    id: 'bopath-falls',
    name: 'Bopath Falls',
    location: 'Kuruwita',
    difficulty: 'Easy',
    description: "A beautiful waterfall shaped like the sacred Bo leaf (Ficus religiosa). Located near Ratnapura, it's a popular spot for locals and offers a refreshing atmosphere in a lush jungle setting.",
    elevation: '100m',
    duration: '1 Hour',
    climate: 'Humid & Lush',
    hiddenGem: false,
    image: require('@/assets/images/bopath.jpeg'),
    safetyTips: ['Crowded on weekends.', 'Rocks are slippery.'],
  },
  // =========================================================================
  // New Popular Trails
  // =========================================================================
  {
    id: 'lake-gregory',
    name: 'Lake Gregory',
    location: 'Nuwara Eliya',
    difficulty: 'Easy',
    description: 'A scenic lake situated in the heart of Nuwara Eliya. Constructed during the British era by Sir William Gregory, it is a hub for recreational water sports and leisurely strolls. The surrounding park features beautiful flower gardens and paved pathways set against a backdrop of mist-covered hills.',
    elevation: '1,868m',
    duration: '2 Hours',
    climate: 'Cool & Misty',
    hiddenGem: false,
    image: require('@/assets/images/gregory.jpeg'),
    images: [
      require('@/assets/images/gregory.jpeg'),
      require('@/assets/images/gregory_2.jpeg'),
      require('@/assets/images/gregory_3.jpeg'),
    ],
    coordinates: { lat: 6.9634, lon: 80.7818 },
    safetyTips: ['Stay on designated walkways.', 'Boating activities require life jackets.'],
  },
  {
    id: 'bakers-falls',
    name: "Baker's Falls",
    location: 'Horton Plains National Park',
    difficulty: 'Easy',
    description: 'A famous waterfall located inside the Horton Plains National Park, named after Sir Samuel Baker. It cascades down a wide, multi-tiered black rock face surrounded by lush montane forest and Rhododendron trees. The loop trail leading to the waterfall is a scenic path rich in Sri Lankan highland biodiversity.',
    elevation: '2,130m',
    duration: '2 Hours',
    climate: 'Cool & Windy',
    hiddenGem: false,
    image: require('@/assets/images/bakersfall.jpeg'),
    coordinates: { lat: 6.7972, lon: 80.7906 },
    safetyTips: ['Rocks near the viewing platform are slippery.', 'Do not venture off the marked path.'],
  },
  {
    id: 'st-clairs-falls',
    name: "St. Clair's Falls",
    location: 'Talawakele',
    difficulty: 'Easy',
    description: 'Widely known as the "Little Niagara of Sri Lanka," this majestic double-cascade waterfall flows through scenic tea plantations. It consists of two segments, Maha Ella and Kuda Ella, which combine to create a breathtaking panorama. The waterfall is easily visible from viewpoints along the Hatton-Talawakele road.',
    elevation: '1,198m',
    duration: '1 Hour',
    climate: 'Cool & Misty',
    hiddenGem: false,
    image: require('@/assets/images/st.jpeg'),
    coordinates: { lat: 6.9372, lon: 80.6456 },
    safetyTips: ['Observe from designated roadside viewpoints.', 'Do not attempt to descend to the pool.'],
  },
  {
    id: 'bomburu-ella',
    name: 'Bomburu Ella',
    location: 'Uva Paranagama',
    difficulty: 'Moderate',
    description: 'Also known as Perawella Falls, this is one of the widest waterfalls in Sri Lanka, consisting of several small jungle cascades joined together. The hike passes through scenic agricultural valleys and thick reserve forests before reaching the thundering base of the fall. The massive spray creates a constant cooling mist.',
    elevation: '1,500m',
    duration: '2 Hours',
    climate: 'Cool & Breezy',
    hiddenGem: false,
    image: require('@/assets/images/bomburu.jpeg'),
    coordinates: { lat: 6.9248, lon: 80.8653 },
    safetyTips: ['The water currents at the base are deceptively strong.', 'Wear slip-resistant shoes for the forest trek.'],
  },
  {
    id: 'lovers-leap',
    name: "Lover's Leap Waterfall",
    location: 'Nuwara Eliya',
    difficulty: 'Easy',
    description: 'A beautiful, rocky waterfall cascading down a high cliff face on the slopes of Pidurutalagala Mountain. According to folklore, the fall is named after a young couple who jumped to their deaths from the top. The walk to the waterfall passes through tea estates and offers panoramic views of the town below.',
    elevation: '1,900m',
    duration: '1 Hour',
    climate: 'Cool & Misty',
    hiddenGem: false,
    image: require('@/assets/images/lov.jpeg'),
    coordinates: { lat: 6.9692, lon: 80.7936 },
    safetyTips: ['Stay clear of the edge at the top viewpoint.', 'Avoid visiting during heavy rain due to flash floods.'],
  },
  {
    id: 'dunhinda-falls',
    name: 'Dunhinda Falls',
    location: 'Badulla',
    difficulty: 'Easy',
    description: "One of Sri Lanka's most iconic waterfalls, named after the smoky spray it creates as it plunges into the canyon below. The 1.5 km trail leading to the fall is a lively forest path filled with local vendors and wild monkeys. Reaching the main viewing deck reveals the raw power of the Badulu Oya river cascading 64 meters.",
    elevation: '550m',
    duration: '2 Hours',
    climate: 'Warm & Humid',
    hiddenGem: false,
    image:  require('@/assets/images/dunhida.jpeg'),
    coordinates: { lat: 7.0217, lon: 81.0628 },
    safetyTips: ['Beware of monkeys along the trail.', 'Do not attempt to cross the safety barriers near the pool.'],
  },

  // =========================================================================
  // New Hidden Gems
  // =========================================================================
  {
    id: 'idalgashinna',
    name: 'Idalgashinna',
    location: 'Haputale',
    difficulty: 'Moderate',
    description: 'A remote railway station and mountain gap famous for its dramatic climatic contrast, where one side of the ridge can be sunny while the other is enveloped in thick fog. Trekking along the railway track offers views of cliffs, pine forests, and tea estates. It is a dream destination for hikers seeking peace amidst the clouds.',
    elevation: '1,615m',
    duration: '3 Hours',
    climate: 'Misty & Chilly',
    hiddenGem: true,
    image: require('@/assets/images/idalagashinna.jpeg'),
    coordinates: { lat: 6.7844, lon: 80.8931 },
    safetyTips: ['Watch for oncoming trains on the narrow tracks.', 'Carry a flashlight as mist can reduce visibility instantly.'],
  },
  {
    id: 'pattipola',
    name: 'Pattipola',
    location: 'Nuwara Eliya',
    difficulty: 'Easy',
    description: 'Known as the highest railway station in Sri Lanka, Pattipola is a gateway to Horton Plains and the misty highland forests. The area is filled with green pine woods, montane grasslands, and quiet walking paths that capture the chill of the mountains. Hiking here feels incredibly serene, away from popular tourist spots.',
    elevation: '1,898m',
    duration: '2 Hours',
    climate: 'Cold & Misty',
    hiddenGem: true,
    image:require('@/assets/images/pattipola.jpeg'),
    coordinates: { lat: 6.8539, lon: 80.8358 },
    safetyTips: ['Layer up, temperatures can drop rapidly.', 'Respect railway regulations when walking near the tracks.'],
  },
  {
    id: 'diyatalawa',
    name: 'Diyatalawa Pine Forest',
    location: 'Diyatalawa',
    difficulty: 'Easy',
    description: 'A charming garrison town nestled in the central highlands, known for its pristine pine forests and rolling grasslands. The walking trails winding through the pine trees offer a refreshing scent and a tranquil escape. The breezy, mild climate makes it an ideal spot for peaceful morning walks and nature photography.',
    elevation: '1,220m',
    duration: '2 Hours',
    climate: 'Cool & Breezy',
    hiddenGem: true,
    image: require('@/assets/images/diyatha.jpeg'),
    coordinates: { lat: 6.8189, lon: 80.9575 },
    safetyTips: ['Stay on public pathways.', 'Leech protection is recommended during wet seasons.'],
  },
  {
    id: 'gerandigini-ella',
    name: 'Gerandigini Ella',
    location: 'Kalupahana',
    difficulty: 'Hard',
    description: 'A stunning, multi-tiered waterfall hidden deep within the Kalupahana mountain range. The trek is challenging, taking adventurers through rugged tea estates, steep pine slopes, and thick undergrowth. Because of its remote location, this fall is rarely visited, ensuring a pristine wilderness experience.',
    elevation: '1,150m',
    duration: '3 Hours',
    climate: 'Misty & Cool',
    hiddenGem: true,
    image: require('@/assets/images/geradigini.jpeg'),
    coordinates: { lat: 6.7881, lon: 80.8256 },
    safetyTips: ['Steep and slippery rocks require careful climbing.', 'Hike with an experienced guide due to unmarked trails.'],
  },
  {
    id: 'aberdeen-falls',
    name: 'Aberdeen Falls',
    location: 'Ginigathena',
    difficulty: 'Moderate',
    description: 'A breathtaking 98-meter waterfall nestled in a deep jungle valley near Ginigathena. The trail descends through thick tropical foliage and rocky steps, leading to a majestic viewing pool surrounded by high rock cliffs. The massive flow of the Kehelgamu Oya river creates a dramatic, thundering display.',
    elevation: '600m',
    duration: '2 Hours',
    climate: 'Humid & Tropical',
    hiddenGem: true,
    image:  require('@/assets/images/aberdeen.jpeg'),
    coordinates: { lat: 6.9458, lon: 80.5019 },
    safetyTips: ['Swimming in the pool is extremely dangerous due to underwater currents.', 'Keep a look out for leeches along the damp path.'],
  },
  {
    id: 'laxapana-falls',
    name: 'Laxapana Falls',
    location: 'Maskeliya',
    difficulty: 'Moderate',
    description: 'A majestic 126-meter waterfall that cascades down a sheer black rock face, famous in Sri Lankan history. The hike to the base of the fall involves climbing down a series of concrete and natural steps surrounded by coffee-colored pools and lush green foliage. The massive plunge pool at the bottom is highly impressive, with mist spraying across the valley.',
    elevation: '700m',
    duration: '2 Hours',
    climate: 'Misty & Humid',
    hiddenGem: true,
    image:  require('@/assets/images/laxapana.jpeg'),
    coordinates: { lat: 6.9011, lon: 80.5303 },
    safetyTips: ['Do not swim in the deep plunge pool.', 'Steps can be slippery when wet.'],
  },
  {
    id: 'madulsima',
    name: "Madulsima Mini World's End",
    location: 'Madulsima',
    difficulty: 'Hard',
    description: 'A breathtaking mountaintop area renowned for the "Mini World\'s End" viewpoint and its endless sea of clouds. The trail winds through remote tea estates and high-altitude grasslands that are frequently swallowed by thick, fast-moving fog. Standing on the edge of the cliff offers an unmatched panoramic experience.',
    elevation: '1,100m',
    duration: '4 Hours',
    climate: 'Cold & Misty',
    hiddenGem: true,
    image:require('@/assets/images/madolsima.jpeg'),
    coordinates: { lat: 7.0867, lon: 81.1517 },
    safetyTips: ['Mist can obscure the steep cliff edge instantly; stay behind markers.', 'Strong winds can be hazardous near the precipice.'],
  },
  {
    id: 'chariot-path',
    name: 'Chariot Path of King Ravana',
    location: 'Ramboda',
    difficulty: 'Hard',
    description: 'A mythical highland grassland plateau believed to be the path Ravana used to carry Sita. Located on the summit of the Ramboda hills, it is characterized by dwarf bamboo forests, rolling plains, and a small pond. The trek is a strenuous climb but rewards hikers with views of the Kotmale valley.',
    elevation: '2,010m',
    duration: '5 Hours',
    climate: 'Cold & Misty',
    hiddenGem: true,
    image: require('@/assets/images/charioth.jpeg'),
    coordinates: { lat: 7.0675, lon: 80.7028 },
    safetyTips: ['Temperatures drop significantly; bring warm clothing.', 'Hire a guide as the path can become completely hidden in thick mist.'],
  },
];
